dir_root: "C:/Z/models/bed/downloaded_data/examples"
dir_outputs: "outputs"
path_example_data_set: "C:/Z/models/bed/downloaded_data/examples/example_data.csv"
path_temperature_ncdf: "C:/Z/models/bed_data/wrfout_d03_2014-08-09_Morocco_2014.nc"
